project_id = "bqnzofttwsuxcucbyxov"

[functions.email-processor]
verify_jwt = false

[functions.whatsapp-sender]
verify_jwt = false

[functions.whatsapp-healthcheck]
verify_jwt = false

[functions.gmail-actions]
verify_jwt = false

[functions.email-summary]
verify_jwt = false

[functions.sync-sheets-rules]
verify_jwt = false

[functions.gmail-sync]
verify_jwt = false

[functions.gmail-oauth-start]
verify_jwt = false

[functions.gmail-oauth-callback]
verify_jwt = false

[functions.email-summary-cron]
verify_jwt = false

[functions.gmail-calendar]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
